---
kind: Service
apiVersion: v1
metadata:
  name: scoring-service-2
spec:
  selector:
    app: xgboost
    model: "2"
  ports:
  - protocol: "TCP"
    # Port accessible inside cluster
    port: 8080
    # Port to forward to inside the pod
    targetPort: 80
    # Port accessible outside cluster
    nodePort: 30002
  type: LoadBalancer



---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scoring-deployment-2
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: xgboost
        model: "2"
    spec:
      containers:
      - name: xgboost-scorer
        image: shengshuyang/xgboost-scorer:0.0.3
        command: [ "python", "xgboost.py" ]
        env:
        - name: MODEL_ID
          value: "model_id is 2"
        ports:
        - containerPort: 80