apiVersion: v1
kind: Pod
metadata:
  name: xgboost-pod
  labels:
    app: xgboost
    model: "2"
spec:
  containers:
  - name: xgboost-scorer
    image: shengshuyang/xgboost-scorer:0.0.1
    command: [ "python", "xgboost.py" ]
